config/routes.rb
Rails.application.routes.draw do
 
  resources :messages
  devise_for :users
  get 'about' => 'welcome#about'
  
  root 'welcome#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:name, :company, :phone, :email, :subject, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ScWebpage</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<link href='http://fonts.googleapis.com/css?family=PT+Serif:400,700,400italic,700italic|Vollkorn:400italic,700italic,400,700|Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "SQU@D CREATIVE", root_path %></li>
        <li><%= link_to "Your Squad", about_path %></li>
        <li><%= link_to "Contact Us", new_message_path %></li>

        
        
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


<div class="container">
<%= yield %>
</div>


 

</div>
</body>
</html>

app/views/messages/_form.html.erb
<body class="blue">
<%= simple_form_for(@message) do |f| %>
  <%= f.error_notification %>

<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
  </div>
  
  <div class="form-group">
    <label for="exampleInputCompany">Company</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Company">
  </div>
  <div class="form-group">
    <label for="exampleInputPhone">Phone Number</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Phone">
  </div>
  <div class="form-group">
    <label for="exampleInputSubject">Subject</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Subject">
  </div>
  <div class="form-group">
    <label for="exampleInputBody">Body</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Body">
  </div>
  </form>
  
 <!--  <div class="wrapper">
  <button type="submit" class="btn btn-default">Send Squ@d Your Message</button>
  </div> -->
  
  <div class="wrapper">
  <form action="mailto:ashantetimoll@gmail.com" type="submit" method="POST" enctype="text/plain" class="btn btn-default">Send Squ@d Your Message</form>
  </div>
<% end %>
</body>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Company</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Subject</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.name %></td>
        <td><%= message.company %></td>
        <td><%= message.phone %></td>
        <td><%= message.email %></td>
        <td><%= message.subject %></td>
        <td><%= message.body %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>Contact Squ@d Creative</h1>

<%= render 'form' %>

<div class="wrapper">
<button type="submit" class="btn btn-default"><%= link_to 'HOME', root_path %></button>
</div>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>



<div class="panel panel-primary">
  <div class="panel-heading">

  <%= @message.name %>
</div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
  <%= @message.company %>
</div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
  <%= @message.phone %>
</div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
  <%= @message.email %>
</div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
  <%= @message.subject %>
</div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
 <!--  <%= render 'messages/form' %> -->
  <%= @message.body %>
</div>
</div>

<%= link_to 'Edit Your Message To Squad', edit_message_path(@message) %> 

app/views/welcome/about.html.erb
<body class="blue">
<div class="container">


<h1>ALL ABOUT SQUAD</h1>
<div class="row">
	<div class="col-md-12">
	<p>Squad Creative was born from our desire to provide quality web development to small businesses. We understand what it's like trying to get your idea off the ground and not know exaclty where to turn next. Our unique backgrouds, work and life experiences will help you make your ideas come to life on the web. If you are looking for a knowledgeable, fun, progressive group to get you going, we are your SQUAD! </p>

</div>
</div>	
<h1>MEET YOUR SQUAD</h1>


<div class="row">
  <div class="col-md-4">WALID ASMAR
  
  <p class="headshot"><%= image_tag "wa.jpg", class: "img-responsive", class: "img-circle", width: "100px" %></p>
  <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. </p>
  <a href="https://twitter.com/Coding_Pa_Ti" class="twitter-follow-button" data-show-count="false">Follow @Coding_Pa_Ti</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
  </div>
  <div class="col-md-4">JESSI THOMAS
  
  <p class="headshot"><%= image_tag "jt.jpg", class: "img-responsive", class: "img-circle",width: "100px" %></p>
  <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. </p>
  <a href="https://twitter.com/JessayyyyThomas" class="twitter-follow-button" data-show-count="false">Follow @JessayyyyThomas</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</div>
  <div class="col-md-4">ASHANTE TIMOLL
  <p class="headshot"><%= image_tag "at.jpg", class: "img-responsive", class: "img-circle",width: "100px" %></p> 
  <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. </p>
  <a href="https://twitter.com/CoachTimoll" class="twitter-follow-button" data-show-count="false">Follow @CoachTimoll</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
  </div>
</div>
</div>

  

app/views/welcome/index.html.erb
<body class="about">
<div class="container">
<h1 class="index">YOUR PARTNER IN GROWTH</h1> 
<!-- <h1 class="index">IN GROWTH</h1> -->
	<h4 class="grey-text text-lighten-5 left-align">Web Development & Design Solutions </h4>
    <h3 class="grey-text text-lighten-5 left-align">Simple. &nbsp;  Quick. &nbsp;  Tailored. </h3>
    
    <a class="right below btn-floating btn-large waves-effect waves-light yellow darken-2 hide-on-med-and-down" id="scroll-to-animation"><i class="mdi-navigation-expand-more"></i></a>
</div>